### ISSUE TITLE
NameError: name 'BertForJointSpanExtractAndClassification' is not defined

### ISSUE THREAD

**Issue by Jztsbo** [cwei01/HI-ASA#2]
Hello,when I run code,I meet this error “NameError: name 'BertForJointSpanExtractAndClassification' is not defined”.I also cannot find this class in the modeling.py.Could you tell me how to solve this problem,please? ：）
Detail Error Information:
Traceback (most recent call last):
  File "E:\anaconda\envs\HIASA\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\anaconda\envs\HIASA\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\code\nlp\HI-ASA\main\run_joint_span.py", line 586, in <module>
    main()
  File "E:\code\nlp\HI-ASA\main\run_joint_span.py", line 473, in main
    model = BertForJointSpanExtractAndClassification(bert_config,args)
NameError: name 'BertForJointSpanExtractAndClassification' is not defined

**Comment by Caliiiiii** [comment]
I also can't find the Class BertForJointSpanExtractAndClassification
